runmode: 'devel'
session.store: 'file'
client.text_editor: 'textmate'

storages:
    default: 
        url: 'db:sqlite://var/db.sqlite'
    
set devel:
    template.cache.disable: true
    debugger.start: true
    debug.console.level: DEBUG